/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'aalmeida' at '9/14/16 10:05 AM' with Gradle 2.11
 *
 * @author aalmeida, @date 9/14/16 10:05 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
